# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ladle < Formula
  desc "Edit cloud storage files with your local editor"
  homepage "https://github.com/jingu/ladle"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jingu/ladle/releases/download/v1.1.0/ladle_1.1.0_darwin_amd64.tar.gz"
      sha256 "950925cede9c1172d61dff21e51f7d05cebb9bbffddaea0c053e392cd073bc2a"

      define_method(:install) do
        bin.install "ladle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jingu/ladle/releases/download/v1.1.0/ladle_1.1.0_darwin_arm64.tar.gz"
      sha256 "d4fd439b1585f8be66775213d2df45e7cae76a9bedd3860d6c01b315ab4a1d90"

      define_method(:install) do
        bin.install "ladle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jingu/ladle/releases/download/v1.1.0/ladle_1.1.0_linux_amd64.tar.gz"
      sha256 "fbf1a027b0dd1aa791d41ff53a5523e63a05d303a7fb1936bfbddb7eb56141fb"
      define_method(:install) do
        bin.install "ladle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jingu/ladle/releases/download/v1.1.0/ladle_1.1.0_linux_arm64.tar.gz"
      sha256 "16c17b8882a5519ec278ff21c949fb5fc4736f7ab13eed184e8a85d5660a02c8"
      define_method(:install) do
        bin.install "ladle"
      end
    end
  end

  test do
    system "#{bin}/ladle", "--version"
  end
end
