# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ladle < Formula
  desc "Edit cloud storage files with your local editor"
  homepage "https://github.com/jingu/ladle"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jingu/ladle/releases/download/v1.2.0/ladle_1.2.0_darwin_amd64.tar.gz"
      sha256 "c024882f3f77536c6d3527520af578f9dec9a7cfef68e3f4f0bce7f494ece5c2"

      define_method(:install) do
        bin.install "ladle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jingu/ladle/releases/download/v1.2.0/ladle_1.2.0_darwin_arm64.tar.gz"
      sha256 "ac5e3940a459cc0eda66edae8d8a49daab63d18757e57bc26ec47a627a390c93"

      define_method(:install) do
        bin.install "ladle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jingu/ladle/releases/download/v1.2.0/ladle_1.2.0_linux_amd64.tar.gz"
      sha256 "db9c24f37e4ea0465478fd65c37f0ab12e82cb2806cbd24fe9204e806848e555"
      define_method(:install) do
        bin.install "ladle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jingu/ladle/releases/download/v1.2.0/ladle_1.2.0_linux_arm64.tar.gz"
      sha256 "857f3f3cd642c5570d1f574644ad8a0c3d9e9855f2a6621c955536d293640f21"
      define_method(:install) do
        bin.install "ladle"
      end
    end
  end

  test do
    system "#{bin}/ladle", "--version"
  end
end
