# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ladle < Formula
  desc "Edit cloud storage files with your local editor"
  homepage "https://github.com/jingu/ladle"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jingu/ladle/releases/download/v1.0.0/ladle_1.0.0_darwin_amd64.tar.gz"
      sha256 "80ac85f07cdf1fa0f0def90a22d586a9e3a965c0a1653bb7e9b9903a5c06c391"

      define_method(:install) do
        bin.install "ladle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jingu/ladle/releases/download/v1.0.0/ladle_1.0.0_darwin_arm64.tar.gz"
      sha256 "242b385d24f65947ab82b9ffc0e9880564911b85a480bc9628dc4e90b5fb4b1a"

      define_method(:install) do
        bin.install "ladle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jingu/ladle/releases/download/v1.0.0/ladle_1.0.0_linux_amd64.tar.gz"
      sha256 "48b3a061706ac9acfba0e4b5fc7951209f3b480fb5409ab3b7ab37466ba49f6b"
      define_method(:install) do
        bin.install "ladle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jingu/ladle/releases/download/v1.0.0/ladle_1.0.0_linux_arm64.tar.gz"
      sha256 "b4b03006e908d005a5381c6e7e81baef6b42d27dce090939310578ae53806bd3"
      define_method(:install) do
        bin.install "ladle"
      end
    end
  end

  test do
    system "#{bin}/ladle", "--version"
  end
end
